// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026. 2. 26. 오후 2:42:59
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Rich/Desktop/team_workflow_build/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rich/Desktop/team_workflow_build/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rich/Desktop/team_workflow_build/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rich/Desktop/team_workflow_build/plugins/**/*.{js,ts,mjs}","C:/Users/Rich/Desktop/team_workflow_build/composables/**/*.{js,ts,mjs}","C:/Users/Rich/Desktop/team_workflow_build/utils/**/*.{js,ts,mjs}","C:/Users/Rich/Desktop/team_workflow_build/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rich/Desktop/team_workflow_build/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rich/Desktop/team_workflow_build/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Rich/Desktop/team_workflow_build/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;